import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My Awesome App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          {/* Add some padding to the top of your main content 
              to prevent it from being hidden behind the fixed header */}
          
            {children}
          
        </main>
      </body>
    </html>
  )
}